# Generated by Django 3.2.7 on 2023-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_cart_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userImage',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
