# Generated by Django 3.2.7 on 2023-03-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20230213_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='transaction_address',
        ),
        migrations.AddField(
            model_name='product',
            name='activeIngredient',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturerAddress',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturerContactNumber',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturerCountry',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturerName',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='route',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
