# Generated by Django 3.2.7 on 2023-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
