# Generated by Django 3.2.7 on 2023-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20230309_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_shopkeeper',
            field=models.BooleanField(choices=[(True, 'Approved'), (False, 'Rejected')], default=False),
        ),
    ]
