# Generated by Django 4.2.1 on 2023-06-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_userprofile_is_shopkeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=5000)),
                ('to_user', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_shopkeeper',
            field=models.BooleanField(choices=[(True, 'Approve'), (False, 'Reject')], default=False),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=5000)),
                ('to_user', models.CharField(max_length=5000)),
                ('message', models.CharField(max_length=50000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.chat')),
            ],
        ),
    ]
