# Generated by Django 4.2.1 on 2023-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shopType',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
