# Generated by Django 4.2.1 on 2023-06-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.CharField(blank=True, default='Approved', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
