# Generated by Django 4.2.1 on 2023-06-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_product_approved_product_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
