# Generated by Django 4.2.1 on 2023-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_product_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to',
            field=models.CharField(blank=True, default='', max_length=50000),
        ),
    ]
