# Generated by Django 4.2.1 on 2023-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product_pk',
            field=models.IntegerField(default=0),
        ),
    ]
