# Generated by Django 4.2.1 on 2023-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(default='', max_length=50000)),
                ('to_user', models.CharField(default='', max_length=50000)),
                ('amount', models.CharField(default='', max_length=50000)),
                ('product', models.CharField(default='', max_length=50000)),
            ],
        ),
    ]
