# Generated by Django 4.2.1 on 2023-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_product_category_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeperName', models.CharField(max_length=255)),
                ('shopkeeperPhone', models.CharField(max_length=20)),
                ('shopkeeperAddress', models.CharField(max_length=255)),
                ('shopType', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_shopkeeper', models.BooleanField(default=False)),
            ],
        ),
    ]
