# Generated by Django 4.2.1 on 2023-07-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_shopkeeper_district_shopkeeper_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopkeeper',
            name='street',
        ),
    ]
