# Generated by Django 4.2.1 on 2023-07-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_remove_shopkeeper_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50000),
        ),
    ]
