# Generated by Django 4.2.1 on 2023-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
