# Generated by Django 4.2.1 on 2023-08-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='realPrice',
            field=models.IntegerField(default=0),
        ),
    ]
