# Generated by Django 4.2.1 on 2023-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_product_count_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
