# Generated by Django 4.2.1 on 2023-08-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
