# Generated by Django 4.2.1 on 2023-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_remove_product_rating_userprofile_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=1200),
        ),
    ]
