# Generated by Django 4.2.1 on 2023-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellname',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
