# Generated by Django 4.2.1 on 2023-08-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_product_sellname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selladdress',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='sellphone',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
