from django.urls import path
from . import views 
# from django.conf.urls import url

urlpatterns = [
    
    path('',views.homepage,name = "homepage"),
    path('register/', views.register,name='register' ),
    path('registerShop/', views.registerShop,name='registerShop' ),
    path('login/', views.user_login, name='login'),
    path('checkLogin/', views.checkLogin, name = "checkLogin"),
    path('checkSignup/', views.checkSignup,name = 'checkSignup'),
    path('checkSignupShopkeeper/', views.checkSignup,name = 'checkSignupShopkeeper'),
    path('logout/', views.user_logout,name = 'logout'),
    path('showLogin/', views.show_login,name = 'showLogin'),
    path('showRegister/', views.show_register,name = 'showRegister'),
    # path('productView/', views.productView,name = 'productView'),
    path('addProduct/', views.addProduct,name = 'addProduct'),
    path('track/<int:pk>', views.productView,name = 'track'),
    path('status/<int:pk>', views.status,name = 'status'),
    path('addToCart/', views.addToCart,name = 'addToCart'),
    path('cart/', views.carts,name = 'cart'),
    path('shop/', views.shop,name = 'shop'),
    path('buy/', views.buy,name = 'buy'),
    path('check/', views.check,name = 'check'),
    path('buyAdd/', views.buyAdd,name = 'buyAdd'),
    path('buyAll/', views.buyAll,name = 'buyAll'),
    path('buy2/', views.buy2,name = 'buy2'),
    path('orders/', views.orders,name = 'orders'),
    path('search/', views.search,name = 'search'),
    path('delete/<int:pk>', views.delete,name = 'delete'),
    path('sendMsg/',views.sendMsg,name = "sendMsg"),
    path('sendMsg1/',views.sendMsg1,name = "sendMsg1"),
    path('showMessages/',views.showMessages,name = "showMessages"),
    path('comment/<int:pk>', views.comments,name = 'comment'),
    path('stock/', views.stock,name = 'stock'),
    path('sell/', views.sell,name = 'sell'),
    path('notifications/', views.notifications,name = 'notifications'),
    path('approve/', views.approve,name = 'approve'),
    path('reject/<int:pk>', views.reject,name = 'reject'),
    path('cartView/<int:pk>', views.cartView,name = 'cartView'),
    path('cartDelete/<int:pk>', views.cartDelete,name = 'cartDelete'),
    path('cartDeleteAll/<int:pk>', views.cartDeleteAll,name = 'cartDeleteAll'),
    path('cancelOrder/<int:pk>', views.cancelOrder,name = 'cancelOrder'),
    path('deleteOrder/<int:pk>', views.deleteOrder,name = 'deleteOrder'),
    path('shopView/', views.shopView,name = 'shopView'),
    path('checkCategory/', views.checkCategory,name = 'checkCategory'),
    path('bill/', views.bill,name = 'bill'),
    path('checkAll/', views.checkAll,name = 'checkAll'),
    path('buyAllAdd/', views.buyAllAdd,name = 'buyAllAdd'),
    path('buyAllBill/', views.buyAllBill,name = 'buyAllBill'),
    path('offer/', views.offer,name = 'offer'),
    path('offers/', views.offers,name = 'offers'),
    path('rating/', views.rating,name = 'rating'),
    path('increase/<int:pk>', views.increase,name = 'increase'),
    path('decrease/<int:pk>', views.decrease,name = 'decrease'),
    path('update/', views.update,name = 'update'),
    ]